name: bidify
region: nyc
services:
- build_command: npm run build
  environment_slug: node-js
  github:
    branch: master
    deploy_on_push: true
    repo: Bidify/BidifyUI
  http_port: 8080
  instance_count: 1
  instance_size_slug: professional-xs
  name: bidify
  routes:
  - path: /
  run_command: npm start -- --hostname 0.0.0.0 --port 8080
